{% set version = "5.0.1" %}

package:
  name: configparser
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/configparser/configparser-{{ version }}.tar.gz
  sha256: 005c3b102c96f4be9b8f40dafbd4997db003d07d1caa19f37808be8031475f2a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools_scm >=3.4.1
    - toml
  run:
    - python >=3.6

test:
  requires:
    - pip
  imports:
    - backports
    - backports.configparser
    - configparser
  commands:
    - pip check

about:
  home: http://docs.python.org/3/library/configparser.html
  license: MIT
  license_file: LICENSE
  summary: Updated configparser from Python 3.8 for Python 2.6+.

extra:
  recipe-maintainers:
    - jakirkham
    - ocefpaf
    - bgruening
